### ISSUE TITLE
Read errors in IOR on Polaris using Bake file backend

### ISSUE THREAD

**Issue by jhendersonHDF** [mochi-hpc/mobject#58] opened 2022-11-22 16:36 UTC
IOR runs successfully on Polaris with Bake's pmem backend, but appears to generate errors on reads with Bake's file backend. I've attached my qsub script and bedrock configuration, as well as the output from running IOR.

[ior_mobject.zip](https://github.com/mochi-hpc/mobject/files/10069309/ior_mobject.zip)

**Comment by carns** [comment] 2022-11-22 19:54
Thanks.  Just to fill in some info on reproducing, I was able to trigger the problem on my laptop, with the na+sm:// transport, using the provided bedrock json file (adjusted to point to /tmp for the backend file), and a single ior process:

`ior -a RADOS -t 64k -b 128k --rados.user=foo --rados.pool=bar --rados.conf=baz`

**Comment by carns** [comment] 2022-11-22 22:22
The `abt_io_pread()` function is in fact reading the correct number of bytes off of disk and they are also being transmitted back to the client successfully by `margo_bulk_transfer()`.  Looks like maybe the amount transferred just isn't being propagated correctly somewhere.

**Comment by carns** [comment] 2022-11-22 22:25
Ah, the `bake_file_read_bulk()` function simply isn't setting the `bytes_read` output argument.  This is a bug in the mochi-bake repo, but I'll hold this open until I push a fix there since this has the reproducer.

**Comment by carns** [comment] 2022-11-23 14:05
Fixed in mochi-bake in https://github.com/mochi-hpc/mochi-bake/pull/58

You'll need to rebuild mobject either with mochi-bake@0.6.4 or a fresh mochi-bake@main to pick up the fix.

**Closed by carns** 2022-11-23 14:05 UTC
